name: Audit
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: 'install'
        run: npm i

      - name: 'build'
        run: npm run build

      - name: 'test'
        run: npm test
        env:
          CI: true

      - name: 'code linting'
        run: npm run lint
