name: Audit1

on:
  push:
    branches: [master]

jobs:

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

       - uses: actions/setup-node@v1 #this will install Node and npm on Ubuntu
      with:
        node-version: '12.x'
      - run: npm install
      - run: npm install -g @angular/cli > /dev/null

      - name: Build
        run: ng build

      - name: Start
        run: ng serve

      - name: Run lint
        run: go tsc --noEmit && eslint . --ext js,ts,json --quiet --fix

      - name: Run tests
        run: ng test
