name: Audit1

on:
  push:
    branches: [master]

jobs:

  audit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build
        run: ng build

      - name: Start
        run: ng serve

      - name: Run lint
        run: go tsc --noEmit && eslint . --ext js,ts,json --quiet --fix

      - name: Run tests
        run: ng test
