name: Audit1

on:
  push:
    branches: [master]

jobs:

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: ng build

      - name: Start
        run: ng serve

      - name: Run lint
        run: go tsc --noEmit && eslint . --ext js,ts,json --quiet --fix

      - name: Run tests
        run: ng test
